name: Publish CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Run tests
        run: yarn test
        env:
          CI: true

  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    needs:
      - build
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          token: "${{ secrets.GITHUB_ACCESS_TOKEN }}"
          fetch-depth: 0
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_ACCESS_TOKEN }}

  publish-to-npm:
    runs-on: ubuntu-18.04
    needs:
      - bump-version
    steps:
      - name: Extract version
        id: version
        uses: olegtarasov/get-tag@v2.1
        with:
          tagRegex: 'v(.*)'

      - name: Set version from release
        uses: reedyuk/npm-version@1.1.1
        with:
          version: ${{ steps.version.outputs.tag }}
          git-tag-version: false

      - name: Create NPM config
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish package
        run: npm publish
