name: Publish CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Run tests
        run: yarn test
        env:
          CI: true

  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    needs: build
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
          fetch-depth: 0
      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

#  publish-to-npm:
#    runs-on: ubuntu-latest
#    needs: bump-version
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#      # Setup .npmrc file to publish to npm
#      - name: Publish package
#        uses: actions/setup-node@v3
#        with:
#          node-version: '16.x'
#          registry-url: 'https://registry.npmjs.org'
#      - run: npm ci
#      - run: npm publish
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
